### ISSUE TITLE
NumPy Error

### ISSUE THREAD

**Issue by thirtyfiveblack** [f1stuff/f1-live-data#8]
Running the Quick Start section I get errors when trying to start the data capture for either a race in progress or sample

`# docker run -it --rm --network f1-live-data_default -v ${PWD}/saves/partial_saved_data_2023_03_05.txt:/tmp/save.txt data-importer-image dataimporter process-mock-data /tmp/save.txt --influx-url http://influxdb:8086`

Error
Traceback (most recent call last):
  File "/usr/local/bin/dataimporter", line 5, in <module>
    from dataimporter.importer import main
  File "/usr/local/lib/python3.9/site-packages/dataimporter/importer.py", line 10, in <module>
    from fastf1.utils import to_datetime
  File "/usr/local/lib/python3.9/site-packages/fastf1/__init__.py", line 65, in <module>
    from fastf1.events import (get_session,  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/fastf1/events.py", line 169, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/usr/local/lib/python3.9/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/usr/local/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/usr/local/lib/python3.9/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/usr/local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
 

After some googling I attempted to override the numpy==1.26.4 in the requirements.txt and rebuilt the image but no luck

**Comment by n1c0la84** [comment]
I have this issue too. I tried on different machines but with no luck.

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

------------------------------------------------------------------------------------------------------------------------------------------

Solved adding this line to the Dockerfile before 'RUN pip install .' :

RUN pip install numpy==1.26.4

And rebuild the image with the --no-cache option.

**Comment by thirtyfiveblack** [comment]
Thanks! That did the trick, can't get the dashboard working in Grafana now with the sample data but that's a new problem to fix

**Comment by Avc81** [comment]
Hi. While running the command "docker run -it --rm --network f1-live-data_default -v ${PWD}/saves/partial_saved_data_2023_03_05.txt:/tmp/save.txt data-importer-image dataimporter process-mock-data /tmp/save.txt --influx-url http://influxdb:8086", the data runs in the terminal but not in Grafana. Any help would be appreciated.
