### ISSUE TITLE
Error while creating container for data importer

### ISSUE THREAD

**Issue by NotKruxx** [f1stuff/f1-live-data#9]
Traceback (most recent call last):
  File "/usr/local/bin/dataimporter", line 5, in <module>
    from dataimporter.importer import main
  File "/usr/local/lib/python3.9/site-packages/dataimporter/importer.py", line 10, in <module>
    from fastf1.utils import to_datetime
  File "/usr/local/lib/python3.9/site-packages/fastf1/__init__.py", line 65, in <module>
    from fastf1.events import (get_session,  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/fastf1/events.py", line 169, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/usr/local/lib/python3.9/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/usr/local/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/usr/local/lib/python3.9/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/usr/local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

I followed all the instruction but this happen

**Comment by 0xfossman** [comment]
Hi, I have the same issue. Also tried running it locally but i get this error:
ERROR: Package 'dataimporter' requires a different Python: 3.11.2 not in '<3.10,>3.7'

**Comment by NotKruxx** [comment]
I think this repo is dead...

**Comment by sanpei3** [comment]
@NotKruxx  @0xFOSSMan 
I found the root cause, I created path as below.
https://github.com/f1stuff/f1-live-data/pull/11#issue-2934369028

Have a nice F1-Life!!

**Comment by f1stuff** [comment]
Fixed with [PR11](https://github.com/f1stuff/f1-live-data/pull/11). Thanks to @sanpei3

**Comment by NotKruxx** [comment]
@sanpei3 Thank you, i tested it today and it works like charm, however i think we should change the pilot list with tsunoda and lawson
